import build

# Build description for rustc (the mrustc-derived Rust compiler).
# Plain C++14 program plus a small "common" support library; links zlib.

build.includes += ["$(S)/src/include", "$(S)/src", "$(S)/tools/common"]

# version.cpp expects these from the build system; the Makefile filled them
# from `git`, we pin static values so the build stays hermetic.
build.cppflags += [
    "-DVERSION_GIT_ISDIRTY=0",
    '-DVERSION_GIT_FULLHASH="unknown"',
    '-DVERSION_GIT_SHORTHASH="mrustc"',
    '-DVERSION_BUILDTIME="unknown"',
    '-DVERSION_GIT_BRANCH="master"',
]

build.cxxflags += [
    "-std=c++14",
    "-O2",
    "-g",
    "-Wall",
    "-Wno-pessimizing-move",
    "-Wno-misleading-indentation",
    "-Werror=return-type",
    "-Werror=switch",
]

SRC = [
    "$(S)/src/main.cpp",
    "$(S)/src/version.cpp",
    "$(S)/src/memory_dump.cpp",
    "$(S)/src/span.cpp",
    "$(S)/src/rc_string.cpp",
    "$(S)/src/debug.cpp",
    "$(S)/src/ident.cpp",
    "$(S)/src/ast/ast.cpp",
    "$(S)/src/ast/types.cpp",
    "$(S)/src/ast/crate.cpp",
    "$(S)/src/ast/path.cpp",
    "$(S)/src/ast/expr.cpp",
    "$(S)/src/ast/pattern.cpp",
    "$(S)/src/ast/dump.cpp",
    "$(S)/src/parse/parseerror.cpp",
    "$(S)/src/parse/token.cpp",
    "$(S)/src/parse/tokentree.cpp",
    "$(S)/src/parse/interpolated_fragment.cpp",
    "$(S)/src/parse/tokenstream.cpp",
    "$(S)/src/parse/lex.cpp",
    "$(S)/src/parse/ttstream.cpp",
    "$(S)/src/parse/root.cpp",
    "$(S)/src/parse/paths.cpp",
    "$(S)/src/parse/types.cpp",
    "$(S)/src/parse/expr.cpp",
    "$(S)/src/parse/pattern.cpp",
    "$(S)/src/expand/mod.cpp",
    "$(S)/src/expand/macro_rules.cpp",
    "$(S)/src/expand/cfg.cpp",
    "$(S)/src/expand/format_args.cpp",
    "$(S)/src/expand/asm.cpp",
    "$(S)/src/expand/concat.cpp",
    "$(S)/src/expand/stringify.cpp",
    "$(S)/src/expand/file_line.cpp",
    "$(S)/src/expand/derive.cpp",
    "$(S)/src/expand/lang_item.cpp",
    "$(S)/src/expand/std_prelude.cpp",
    "$(S)/src/expand/crate_tags.cpp",
    "$(S)/src/expand/include.cpp",
    "$(S)/src/expand/env.cpp",
    "$(S)/src/expand/test.cpp",
    "$(S)/src/expand/rustc_diagnostics.cpp",
    "$(S)/src/expand/proc_macro.cpp",
    "$(S)/src/expand/assert.cpp",
    "$(S)/src/expand/compile_error.cpp",
    "$(S)/src/expand/codegen.cpp",
    "$(S)/src/expand/doc.cpp",
    "$(S)/src/expand/lints.cpp",
    "$(S)/src/expand/misc_attrs.cpp",
    "$(S)/src/expand/stability.cpp",
    "$(S)/src/expand/panic.cpp",
    "$(S)/src/expand/rustc_box.cpp",
    "$(S)/src/expand/test_harness.cpp",
    "$(S)/src/macro_rules/mod.cpp",
    "$(S)/src/macro_rules/eval.cpp",
    "$(S)/src/macro_rules/parse.cpp",
    "$(S)/src/resolve/use.cpp",
    "$(S)/src/resolve/index.cpp",
    "$(S)/src/resolve/absolute.cpp",
    "$(S)/src/resolve/common.cpp",
    "$(S)/src/hir/from_ast.cpp",
    "$(S)/src/hir/from_ast_expr.cpp",
    "$(S)/src/hir/dump.cpp",
    "$(S)/src/hir/hir.cpp",
    "$(S)/src/hir/hir_ops.cpp",
    "$(S)/src/hir/generic_params.cpp",
    "$(S)/src/hir/crate_ptr.cpp",
    "$(S)/src/hir/expr_ptr.cpp",
    "$(S)/src/hir/type.cpp",
    "$(S)/src/hir/path.cpp",
    "$(S)/src/hir/expr.cpp",
    "$(S)/src/hir/pattern.cpp",
    "$(S)/src/hir/visitor.cpp",
    "$(S)/src/hir/crate_post_load.cpp",
    "$(S)/src/hir/inherent_cache.cpp",
    "$(S)/src/hir_conv/expand_type.cpp",
    "$(S)/src/hir_conv/constant_evaluation.cpp",
    "$(S)/src/hir_conv/resolve_ufcs.cpp",
    "$(S)/src/hir_conv/bind.cpp",
    "$(S)/src/hir_conv/markings.cpp",
    "$(S)/src/hir_conv/lifetime_elision.cpp",
    "$(S)/src/hir_typeck/outer.cpp",
    "$(S)/src/hir_typeck/common.cpp",
    "$(S)/src/hir_typeck/helpers.cpp",
    "$(S)/src/hir_typeck/static.cpp",
    "$(S)/src/hir_typeck/impl_ref.cpp",
    "$(S)/src/hir_typeck/resolve_common.cpp",
    "$(S)/src/hir_typeck/expr_visit.cpp",
    "$(S)/src/hir_typeck/expr_cs.cpp",
    "$(S)/src/hir_typeck/expr_cs__enum.cpp",
    "$(S)/src/hir_typeck/expr_check.cpp",
    "$(S)/src/hir_expand/annotate_value_usage.cpp",
    "$(S)/src/hir_expand/closures.cpp",
    "$(S)/src/hir_expand/ufcs_everything.cpp",
    "$(S)/src/hir_expand/reborrow.cpp",
    "$(S)/src/hir_expand/erased_types.cpp",
    "$(S)/src/hir_expand/vtable.cpp",
    "$(S)/src/hir_expand/static_borrow_constants.cpp",
    "$(S)/src/hir_expand/lifetime_infer.cpp",
    "$(S)/src/mir/mir.cpp",
    "$(S)/src/mir/mir_ptr.cpp",
    "$(S)/src/mir/dump.cpp",
    "$(S)/src/mir/helpers.cpp",
    "$(S)/src/mir/visit_crate_mir.cpp",
    "$(S)/src/mir/from_hir.cpp",
    "$(S)/src/mir/from_hir_match.cpp",
    "$(S)/src/mir/mir_builder.cpp",
    "$(S)/src/mir/check.cpp",
    "$(S)/src/mir/cleanup.cpp",
    "$(S)/src/mir/optimise.cpp",
    "$(S)/src/mir/check_full.cpp",
    "$(S)/src/mir/borrow_check.cpp",
    "$(S)/src/hir/serialise.cpp",
    "$(S)/src/hir/deserialise.cpp",
    "$(S)/src/hir/serialise_lowlevel.cpp",
    "$(S)/src/trans/trans_list.cpp",
    "$(S)/src/trans/mangling_v2.cpp",
    "$(S)/src/trans/enumerate.cpp",
    "$(S)/src/trans/auto_impls.cpp",
    "$(S)/src/trans/monomorphise.cpp",
    "$(S)/src/trans/codegen.cpp",
    "$(S)/src/trans/codegen_c.cpp",
    "$(S)/src/trans/codegen_c_structured.cpp",
    "$(S)/src/trans/codegen_mmir.cpp",
    "$(S)/src/trans/target.cpp",
    "$(S)/src/trans/allocator.cpp",
]

COMMON = [
    "$(S)/tools/common/toml.cpp",
    "$(S)/tools/common/path.cpp",
    "$(S)/tools/common/debug.cpp",
    "$(S)/tools/common/jobserver.cpp",
]

rustc = program(
    srcs=SRC + COMMON,
    name="rustc",
    ldflags=["-lz"],
)

install(rustc)

