#!/usr/bin/env python3
"""Generate reference vectors for bin/rustc/float128_ut.cpp.

Every expected value is computed with exact rational arithmetic and rounded
to IEEE binary128 (or binary64/32) with round-to-nearest, ties-to-even —
independently of any host float support. The build runs this as the
`float128_ut_vectors` node; the table is generated into the build tree, not
checked in.

    dev/gen_float128_vectors.py [OUTPUT.inc]
"""

import contextlib
import os
import sys
from fractions import Fraction

EXP_BITS = 15
BIAS = 16383
MANT = 112
MIN_EXP = -16382
MAX_EXP = 16383


def round_to_format(value: Fraction, mant: int, min_exp: int, max_exp: int, bias: int):
    """Round an exact nonzero rational to (biased_exponent, fraction) bits."""
    sign = 0
    if value < 0:
        sign = 1
        value = -value
    e = value.numerator.bit_length() - value.denominator.bit_length()
    while Fraction(2) ** e > value:
        e -= 1
    while Fraction(2) ** (e + 1) <= value:
        e += 1
    if e < min_exp:
        e = min_exp
    scaled = value / Fraction(2) ** (e - mant)
    whole = scaled.numerator // scaled.denominator
    rem = scaled - whole
    if rem > Fraction(1, 2) or (rem == Fraction(1, 2) and whole % 2 == 1):
        whole += 1
    if whole >= 2 ** (mant + 1):
        whole >>= 1
        e += 1
    if e > max_exp:
        return sign, (1 << EXP_BITS) - 1 if mant == MANT else None, "inf"
    if whole >= 2 ** mant:
        return sign, e + bias, whole - 2 ** mant
    return sign, 0, whole


def f128_bits(value: Fraction, negative_zero: bool = False) -> int:
    if value == 0:
        return (1 << 127) if negative_zero else 0
    sign, biased, frac = round_to_format(value, MANT, MIN_EXP, MAX_EXP, BIAS)
    if frac == "inf":
        return (sign << 127) | (0x7FFF << 112)
    return (sign << 127) | (biased << 112) | frac


def f64_bits(value: Fraction, negative_zero: bool = False) -> int:
    if value == 0:
        return (1 << 63) if negative_zero else 0
    sign, biased, frac = round_to_format(value, 52, -1022, 1023, 1023)
    if frac == "inf" or biased > 0x7FE:
        return (sign << 63) | (0x7FF << 52)
    return (sign << 63) | (biased << 52) | frac


def f32_bits(value: Fraction, negative_zero: bool = False) -> int:
    if value == 0:
        return (1 << 31) if negative_zero else 0
    sign, biased, frac = round_to_format(value, 23, -126, 127, 127)
    if frac == "inf" or biased > 0xFE:
        return (sign << 31) | (0xFF << 23)
    return (sign << 31) | (biased << 23) | frac


def f128_value(bits: int) -> Fraction:
    sign = -1 if bits >> 127 else 1
    biased = (bits >> 112) & 0x7FFF
    frac = bits & (2 ** 112 - 1)
    assert biased != 0x7FFF, "specials are covered by handwritten tests"
    if biased == 0:
        return sign * frac * Fraction(2) ** (MIN_EXP - MANT)
    return sign * (frac + 2 ** 112) * Fraction(2) ** (biased - BIAS - MANT)


def hi_lo(bits: int) -> str:
    return f"0x{bits >> 64:016x}ull, 0x{bits & (2 ** 64 - 1):016x}ull"


def lcg_bits(state: int) -> tuple[int, int]:
    """Deterministic pattern generator; avoids specials."""
    state = (state * 6364136223846793005 + 1442695040888963407) % 2 ** 64
    hi = state
    state = (state * 6364136223846793005 + 1442695040888963407) % 2 ** 64
    lo = state
    # Keep the exponent in a moderate range and clear the sign sometimes
    biased = 16383 - 512 + (hi >> 49) % 1024
    hi = (hi & 0x8000_FFFF_FFFF_FFFF) & ~(0x7FFF << 48) | (biased << 48)
    return (hi << 64) | lo, state


def operands() -> list[int]:
    fixed = [
        f128_bits(Fraction(1)),
        f128_bits(Fraction(-1)),
        f128_bits(Fraction(3, 2)),
        f128_bits(Fraction(1, 3)),
        f128_bits(Fraction(1, 10)),
        f128_bits(Fraction(10) ** 30),
        f128_bits(-Fraction(10) ** -30),
        f128_bits(Fraction(2) ** 16000),
        f128_bits(Fraction(2) ** -16000),
        f128_bits(Fraction(2) ** -16382),          # min normal
        (0x7FFE << 112) | (2 ** 112 - 1),           # max normal
        1,                                          # min subnormal
        (1 << 111),                                 # mid subnormal
        (0x0000_8000_0000_0000 << 64) | 12345,      # subnormal with tail
        f128_bits(Fraction(2) ** 60 + 1),           # integer with low bit
        f128_bits(Fraction(7)),
        f128_bits(Fraction(-2, 3)),
        (0x3FFF << 112) | (2 ** 112 - 1),           # 1 + full mantissa
    ]
    state = 12345
    for _ in range(24):
        bits, state = lcg_bits(state)
        fixed.append(bits)
    return fixed


def trunc_fraction(v: Fraction) -> Fraction:
    return Fraction(v.numerator // v.denominator) if v >= 0 else -Fraction((-v).numerator // (-v).denominator)


def main() -> None:
    print("// Generated by dev/gen_float128_vectors.py; do not edit by hand.")
    print()

    ops = operands()
    values = [(bits, f128_value(bits)) for bits in ops]

    print("static const BinaryOpVector binary_op_vectors[] = {")
    count = 0
    for i, (abits, a) in enumerate(values):
        for j in range(i, len(values)):
            bbits, b = values[j]
            # Keep every fixed pair; thin pairs with generated operands
            if (i * 31 + j * 17) % 7 != 0 and j >= len(values) - 24:
                continue
            product_negative = (a < 0) != (b < 0)
            add = f128_bits(a + b)
            sub = f128_bits(a - b)
            mul = f128_bits(a * b, product_negative)
            div = f128_bits(a / b, product_negative)
            # C fmod: the result carries the dividend's sign, zero included
            fmod = f128_bits(a - b * trunc_fraction(a / b), a < 0)
            print(f"    {{{hi_lo(abits)}, {hi_lo(bbits)},")
            print(f"     {hi_lo(add)}, {hi_lo(sub)},")
            print(f"     {hi_lo(mul)}, {hi_lo(div)}, {hi_lo(fmod)}}},")
            count += 1
    print("};")
    print()

    print("static const ConvertVector convert_vectors[] = {")
    for bits, v in values:
        d = f64_bits(v, v < 0)
        f = f32_bits(v, v < 0)
        as_i64 = max(min(trunc_fraction(v), 2 ** 63 - 1), -(2 ** 63))
        as_u64 = max(min(trunc_fraction(v), 2 ** 64 - 1), 0)
        i64_text = "INT64_MIN" if as_i64 == -(2 ** 63) else f"INT64_C({as_i64})"
        print(f"    {{{hi_lo(bits)}, 0x{d:016x}ull, 0x{f:08x}u, "
              f"{i64_text}, UINT64_C({as_u64})}},")
    print("};")
    print()

    parse_cases = [
        "0", "1", "2", "10", "100000000000000000000000000000000000000",
        "0.5", "0.1", "0.125", "3.14159265358979323846264338327950288",
        "1e10", "1e-10", "1e300", "1e-300", "1e4932", "1e-4932", "1e-4965",
        "1e5000", "1e-5000", "2.2250738585072014e-308",
        "340282366920938463463374607431768211455.999",
        "0.000000000000000000000000000000000000000000001",
        "9999999999999999999999999999999999999999e-20",
        "1.18973149535723176508575932662800702e4932",
        "6.475175119438025110924438958227646552e-4966",
    ]
    print("static const ParseVector parse_vectors[] = {")
    for text in parse_cases:
        if "e" in text:
            mant, _, exp = text.partition("e")
            value = Fraction(mant) * Fraction(10) ** int(exp)
        else:
            value = Fraction(text)
        print(f'    {{"{text}", {hi_lo(f128_bits(value))}}},')
    print("};")
    print()

    print("static const RoundingVector rounding_vectors[] = {")
    for bits, v in values:
        floor_v = trunc_fraction(v) if v >= 0 or trunc_fraction(v) == v else trunc_fraction(v) - 1
        ceil_v = trunc_fraction(v) if v <= 0 or trunc_fraction(v) == v else trunc_fraction(v) + 1
        frac = v - trunc_fraction(v)
        if abs(frac) < Fraction(1, 2):
            round_v = trunc_fraction(v)
        elif abs(frac) > Fraction(1, 2):
            round_v = trunc_fraction(v) + (1 if v > 0 else -1)
        else:
            round_v = trunc_fraction(v) + (1 if v > 0 else -1)
        if abs(frac) != Fraction(1, 2):
            round_even_v = round_v
        else:
            round_even_v = trunc_fraction(v) if trunc_fraction(v) % 2 == 0 else trunc_fraction(v) + (1 if v > 0 else -1)
        # IEEE: rounding a negative value to a zero result gives -0
        neg = v < 0
        print(f"    {{{hi_lo(bits)}, {hi_lo(f128_bits(trunc_fraction(v), neg))},")
        print(f"     {hi_lo(f128_bits(floor_v, neg))}, {hi_lo(f128_bits(ceil_v, neg))},")
        print(f"     {hi_lo(f128_bits(round_v, neg))}, {hi_lo(f128_bits(round_even_v, neg))}}},")
    print("};")
    print()

    def format_g(v: Fraction, significant: int) -> str:
        if v == 0:
            return "0"
        out = "-" if v < 0 else ""
        m = abs(v)
        e10 = 0
        while m >= 10:
            m /= 10
            e10 += 1
        while m < 1:
            m *= 10
            e10 -= 1
        scaled = abs(v) * Fraction(10) ** (significant - 1 - e10)
        digits = scaled.numerator // scaled.denominator
        rem = scaled - digits
        if rem > Fraction(1, 2) or (rem == Fraction(1, 2) and digits % 2 == 1):
            digits += 1
        text = str(digits)
        if len(text) > significant:
            text = text[:-1]
            e10 += 1
        text = text.rstrip("0") or "0"
        if e10 < -4 or e10 >= significant:
            body = text[0] + ("." + text[1:] if len(text) > 1 else "")
            return f"{out}{body}e{e10:+03d}"
        if e10 < 0:
            return f"{out}0.{'0' * (-e10 - 1)}{text}"
        if e10 + 1 >= len(text):
            return f"{out}{text}{'0' * (e10 + 1 - len(text))}"
        return f"{out}{text[: e10 + 1]}.{text[e10 + 1:]}"

    print("static const FormatVector format_vectors[] = {")
    for bits, v in values:
        print(f'    {{{hi_lo(bits)}, "{format_g(v, 6)}"}},')
    print("};")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        os.makedirs(os.path.dirname(os.path.abspath(sys.argv[1])), exist_ok=True)
        with open(sys.argv[1], "w") as output:
            with contextlib.redirect_stdout(output):
                main()
    else:
        main()
