#!/usr/bin/env python3
"""Emit the Unicode tables canonical composition needs, from Python's own data.

    gen_unicode_nfc.py <out.inc>

Three sorted tables: the non-zero canonical combining classes, the canonical
decompositions (one or two codepoints each), and the composition pairs that
compose back. A pair is included only when Python's NFC recomposes it, which is
how the composition exclusions are honoured without carrying that list.
"""
import sys
import unicodedata

# Hangul is composed arithmetically rather than from a table.
HANGUL_S_BASE = 0xAC00
HANGUL_L_BASE = 0x1100
HANGUL_V_BASE = 0x1161
HANGUL_T_BASE = 0x11A7
HANGUL_L_COUNT = 19
HANGUL_V_COUNT = 21
HANGUL_T_COUNT = 28
HANGUL_N_COUNT = HANGUL_V_COUNT * HANGUL_T_COUNT
HANGUL_S_COUNT = HANGUL_L_COUNT * HANGUL_N_COUNT

MAX_CODEPOINT = 0x110000


def canonicalDecomposition(codepoint):
    text = unicodedata.decomposition(chr(codepoint))
    if not text or text.startswith("<"):
        return None
    return [int(part, 16) for part in text.split()]


def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: gen_unicode_nfc.py <out.inc>")

    combining = []
    decompositions = []
    compositions = []

    for codepoint in range(MAX_CODEPOINT):
        if HANGUL_S_BASE <= codepoint < HANGUL_S_BASE + HANGUL_S_COUNT:
            continue

        character = chr(codepoint)
        cls = unicodedata.combining(character)
        if cls != 0:
            combining.append((codepoint, cls))

        parts = canonicalDecomposition(codepoint)
        if parts is None:
            continue
        if len(parts) == 1:
            decompositions.append((codepoint, parts[0], 0))
            continue
        if len(parts) != 2:
            raise SystemExit(f"U+{codepoint:04X}: canonical decomposition of {len(parts)} parts")
        decompositions.append((codepoint, parts[0], parts[1]))
        # Only a pair that NFC puts back together may be composed: that is what
        # the composition exclusions and the non-starter rule come to.
        if unicodedata.normalize("NFC", chr(parts[0]) + chr(parts[1])) == character:
            compositions.append((parts[0], parts[1], codepoint))

    combining.sort()
    decompositions.sort()
    compositions.sort()

    with open(sys.argv[1], "w", encoding="utf-8") as out:
        out.write("// Generated by dev/gen_unicode_nfc.py -- do not edit.\n")
        out.write(f"// Unicode {unicodedata.unidata_version}\n")

        out.write(f"static const UnicodeCombining COMBINING[{len(combining)}] = {{\n")
        for codepoint, cls in combining:
            out.write(f"    {{0x{codepoint:04X}, {cls}}},\n")
        out.write("};\n")

        out.write(f"static const UnicodeDecomposition DECOMPOSITIONS[{len(decompositions)}] = {{\n")
        for codepoint, first, second in decompositions:
            out.write(f"    {{0x{codepoint:04X}, 0x{first:04X}, 0x{second:04X}}},\n")
        out.write("};\n")

        out.write(f"static const UnicodeComposition COMPOSITIONS[{len(compositions)}] = {{\n")
        for first, second, composed in compositions:
            out.write(f"    {{0x{first:04X}, 0x{second:04X}, 0x{composed:04X}}},\n")
        out.write("};\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
