#!/usr/bin/env python3
"""Check that rustc-compatible -C options drive cfg, MIR, and C codegen."""

import os
from pathlib import Path
import re
import shlex
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
import lib  # noqa: E402


def invoke(rustc: str, src: str, output: str, args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        lib.wrap_gdb([rustc, src, "--crate-type", "lib", "-o", output, *args]),
        env=dict(os.environ),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )


def expect_ok(result: subprocess.CompletedProcess[str], what: str) -> None:
    if result.returncode != 0:
        sys.stdout.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise RuntimeError(f"{what} failed with exit {result.returncode}")


def expect_error(result: subprocess.CompletedProcess[str], what: str, needle: str) -> None:
    if result.returncode == 0:
        raise RuntimeError(f"{what} was accepted")
    if needle not in result.stderr:
        sys.stderr.write(result.stderr)
        raise RuntimeError(f"{what} did not report {needle!r}")


def compile_mir(rustc: str, src: str, work: str, name: str, args: list[str]) -> str:
    output = os.path.join(work, name)
    result = invoke(
        rustc,
        src,
        output,
        ["--crate-name", "codegen_options", "-Zdump-mir", "-Zstop-after=mir", *args],
    )
    expect_ok(result, name)
    return Path(output + "_3_mir.rs").read_text()


def ordinary_call_is_inlined(mir: str) -> bool:
    marker = 'fn ::"codegen_options"::ordinary_call('
    start = mir.find(marker)
    if start < 0:
        raise RuntimeError("MIR dump has no ordinary_call")
    end = mir.find("\nfn ", start + len(marker))
    body = mir[start:] if end < 0 else mir[start:end]
    return '::"codegen_options"::ordinary(' not in body


def check_cfg(rustc: str, src: str, work: str, name: str, expected: bool, args: list[str]) -> None:
    expectation = "expect_debug_assertions" if expected else "expect_no_debug_assertions"
    result = invoke(
        rustc,
        src,
        os.path.join(work, name),
        ["-Zstop-after=expand", f"--cfg={expectation}", *args],
    )
    expect_ok(result, name)


def codegen_flags(rustc: str, src: str, work: str, name: str, args: list[str]) -> list[str]:
    output = os.path.join(work, name)
    command_file = output + ".command"
    result = invoke(
        rustc,
        src,
        output,
        [f"-Cemit-build-command={command_file}", *args],
    )
    expect_ok(result, f"C codegen {name}")
    command = shlex.split(Path(command_file).read_text())
    response = next((arg[1:] for arg in command if arg.startswith("@")), None)
    if response is None:
        raise RuntimeError(f"C codegen command has no response file: {command!r}")
    return shlex.split(Path(response).read_text())


def check_codegen_prelude(rustc: str, src: str, work: str) -> None:
    output = os.path.join(work, "prelude")
    result = invoke(rustc, src, output, ["-Cemit-cpp-only"])
    expect_ok(result, "embedded C++ prelude")
    metadata = Path(output)
    if not metadata.is_file() or metadata.stat().st_size == 0:
        raise RuntimeError("emit-cpp-only did not produce loadable rlib metadata")
    query = subprocess.run(
        lib.wrap_gdb([rustc, "--crate-name-of", output]),
        env=dict(os.environ),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    expect_ok(query, "crate metadata name query")
    words = query.stdout.split()
    if not words or words[-1] != Path(src).stem:
        raise RuntimeError(f"metadata crate name is {query.stdout!r}, expected {Path(src).stem!r}")
    generated = Path(output + ".cpp").read_text()
    require_compact_cpp_syntax(generated)
    markers = (
        "#define TRUSTME_CODEGEN_DISALLOW_EMPTY_STRUCTS ",
        "/*\n * AUTOGENERATED by trustme\n */",
        "struct trustme_panic final",
        "static inline u8 __trustme_atomicloop8",
        "static inline f128 f128_add",
    )
    position = 0
    for marker in markers:
        found = generated.find(marker, position)
        if found < 0:
            raise RuntimeError(f"generated C++ prelude has no {marker!r}")
        position = found + len(marker)
    if not generated.startswith(markers[0]):
        raise RuntimeError("generated C++ does not start with the embedded prelude configuration")


def check_link_args(rustc: str, src: str, work: str) -> None:
    output = os.path.join(work, "link-args")
    command_file = output + ".command"
    expected = ["trustme-link-arg-first", "trustme-link-arg-second"]
    result = subprocess.run(
        lib.wrap_gdb([
            rustc,
            src,
            "--crate-type",
            "bin",
            "-o",
            output,
            f"-Cemit-build-command={command_file}",
            f"-Clink-arg={expected[0]}",
            "-C",
            f"link-arg={expected[1]}",
        ]),
        env=dict(os.environ),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )
    expect_ok(result, "link-arg codegen")
    command = shlex.split(Path(command_file).read_text())
    response = next((arg[1:] for arg in command if arg.startswith("@")), None)
    if response is None:
        raise RuntimeError(f"link-arg command has no response file: {command!r}")
    args = shlex.split(Path(response).read_text())
    actual = [arg for arg in args if arg.startswith("trustme-link-arg-")]
    if actual != expected:
        raise RuntimeError(f"link args changed order: {actual!r} != {expected!r}")


def generated_symbol(generated: str, function: str) -> str:
    match = re.search(
        rf"^#define (ZR[0-9a-f]{{16}}) {re.escape(function)}$",
        generated,
        re.MULTILINE,
    )
    if match is None:
        raise RuntimeError(f"generated C++ has no exported function {function}")
    return match.group(1)


def generated_symbol_headers(generated: str, symbol: str) -> list[tuple[int, str]]:
    headers: list[tuple[int, str]] = []
    for match in re.finditer(
        rf"^(?!\s|#)[^\n;=]*\b{re.escape(symbol)}\(",
        generated,
        re.MULTILINE,
    ):
        opening = match.end() - 1
        depth = 1
        cursor = opening + 1
        while cursor < len(generated) and depth:
            if generated[cursor] == "(":
                depth += 1
            elif generated[cursor] == ")":
                depth -= 1
            cursor += 1
        while cursor < len(generated) and generated[cursor].isspace():
            cursor += 1
        if cursor < len(generated) and generated[cursor] in ";{":
            headers.append((match.start(), generated[cursor]))
    return headers


def generated_function_headers(generated: str, function: str) -> list[tuple[int, str]]:
    return generated_symbol_headers(generated, generated_symbol(generated, function))


def generated_function_by_symbol(generated: str, symbol: str) -> str:
    definitions = [
        position
        for position, terminator in generated_symbol_headers(generated, symbol)
        if terminator == "{"
    ]
    if len(definitions) != 1:
        raise RuntimeError(f"generated C++ has {len(definitions)} definitions of {symbol}")
    start = definitions[0]
    end = generated.find("\n}\n", start)
    if end < 0:
        raise RuntimeError(f"generated C++ has no end of function {symbol}")
    return generated[start:end + 3]


def generated_function(generated: str, function: str) -> str:
    return generated_function_by_symbol(generated, generated_symbol(generated, function))


def reject_detailed_codegen_comments(generated: str) -> None:
    patterns = (
        r"^// (?:PROTO|EXTERN|::|struct |enum )",
        r"/\*@\d+\*/",
        r"/\* ?(?:ZST|zst|Niche tag|PhantomData)",
        r";[ \t]+// ",
        r"^[ \t]*// \^ ",
        r"// -> ",
    )
    for pattern in patterns:
        if re.search(pattern, generated, re.MULTILINE):
            raise RuntimeError(f"generated C++ contains detailed comment matching {pattern!r}")


def require_cpp_layout_asserts(generated: str) -> None:
    if "typedef char sizeof_assert_" in generated or "typedef char alignof_assert_" in generated:
        raise RuntimeError("generated C++ still uses typedef layout assertions")
    if "static_assert(sizeof(" not in generated:
        raise RuntimeError("generated C++ has no static layout assertion")


def require_compact_cpp_syntax(generated: str) -> None:
    block_scope = re.search(r"^[ \t]*(?:bb|cleanup_bb)\d+: \{$", generated, re.MULTILINE)
    if block_scope:
        raise RuntimeError(f"generated C++ contains blanket basic-block scope {block_scope.group()!r}")

    joined_functions = re.search(r"^}\n(?:static )?[^\n]*\bZR[0-9a-f]{16}\(", generated, re.MULTILINE)
    if joined_functions:
        raise RuntimeError("generated functions have no separating blank line")

    verbose_cast = re.search(r"\b(?:static|reinterpret|const|dynamic)_cast<", generated)
    if verbose_cast:
        raise RuntimeError(f"generated C++ contains verbose cast {verbose_cast.group()!r}")

    tagged_use = re.search(
        r"\b(?:struct (?:[sex]_ZR[0-9a-f]{16}|t_ZR[0-9a-f]{16}|TUP_[A-Za-z0-9_]+)"
        r"|union u_ZR[0-9a-f]{16})\b(?!\s*[;{])",
        generated,
    )
    if tagged_use:
        raise RuntimeError(f"generated C++ contains redundant type tag {tagged_use.group()!r}")


def check_unwind_cleanup(rustc: str, src: str, work: str) -> None:
    output = os.path.join(work, "unwind-cleanup")
    result = invoke(
        rustc,
        src,
        output,
        ["--crate-name", "codegen_unwind_cleanup", "-Cemit-cpp-only"],
    )
    expect_ok(result, "unwind cleanup codegen")
    generated = Path(output + ".cpp").read_text()
    reject_detailed_codegen_comments(generated)
    require_compact_cpp_syntax(generated)

    no_op = generated_function(generated, "trustme_noop_cleanup_probe")
    if "trustme_run_cleanup" in no_op or "try {" in no_op:
        raise RuntimeError("no-op unwind cleanup emitted EH scaffolding")

    monomorphized_no_op = generated_function(generated, "generic_noop_cleanup")
    if "trustme_run_cleanup" in monomorphized_no_op or "try {" in monomorphized_no_op:
        raise RuntimeError("monomorphized no-drop cleanup emitted EH scaffolding")

    no_op_drop = generated_function(generated, "generic_projected_noop_drop")
    if re.search(r"try \{\s*\} catch", no_op_drop):
        raise RuntimeError("monomorphized no-drop operation emitted an empty handler")
    if re.search(r"if\( df\d+ \) \{\s*\}", no_op_drop):
        raise RuntimeError("monomorphized no-drop operation emitted an empty drop flag test")

    real = generated_function(generated, "trustme_real_cleanup_probe")
    if "auto trustme_run_cleanup" not in real or "try {" not in real:
        raise RuntimeError("real unwind cleanup lost its EH scaffolding")
    if "\n\t\ttrustme_run_cleanup(" not in real:
        raise RuntimeError("real unwind cleanup is not called from the handler")
    if "try { trustme_run_cleanup" in real:
        raise RuntimeError("cleanup runner is redundantly wrapped in try/catch")
    runner_start = real.index("auto trustme_run_cleanup")
    runner_end = real.index("\n\t};", runner_start)
    runner = real[runner_start:runner_end]
    if "noexcept" not in runner:
        raise RuntimeError("cleanup runner does not terminate a second unwind")
    if "catch (...) { abort(); }" in runner:
        raise RuntimeError("cleanup runner contains redundant per-operation handlers")


def check_enum_switch_compaction(rustc: str, src: str, work: str) -> None:
    output = os.path.join(work, "enum-switch")
    result = invoke(
        rustc,
        src,
        output,
        ["--crate-name", "codegen_enum_switch", "-Cemit-cpp-only"],
    )
    expect_ok(result, "enum switch compaction codegen")
    generated = Path(output + ".cpp").read_text()
    reject_detailed_codegen_comments(generated)
    require_compact_cpp_syntax(generated)
    require_cpp_layout_asserts(generated)

    all_same = generated_function(generated, "trustme_all_same_switch")
    if "switch(" in all_same or "case " in all_same:
        raise RuntimeError("single-target enum match emitted a C++ switch")

    one_odd = generated_function(generated, "trustme_one_odd_switch")
    if "switch(" in one_odd or "case " in one_odd:
        raise RuntimeError("one-odd-target enum match emitted a C++ switch")
    if "if(" not in one_odd:
        raise RuntimeError("one-odd-target enum match was not compacted to a condition")


def check_fieldless_enum_derive(
    rustc: str, src: str, libstd_tar: str, work: str
) -> None:
    output = os.path.join(work, "fieldless-enum-derive")
    libstd = lib.untar(libstd_tar, os.path.join(work, "libstd"))
    result = invoke(
        rustc,
        src,
        output,
        [
            "--crate-name", "codegen_fieldless_enum_derive",
            "-L", os.path.join(libstd, "release"),
            "-O",
            "-Cemit-cpp-only",
        ],
    )
    expect_ok(result, "fieldless enum derive codegen")
    generated = Path(output + ".cpp").read_text()
    reject_detailed_codegen_comments(generated)
    require_compact_cpp_syntax(generated)

    for function in (
        "trustme_fieldless_eq",
        "trustme_fieldless_cmp",
        "trustme_fieldless_partial_cmp",
    ):
        wrapper = generated_function(generated, function)
        callee = re.search(r"\brv = (ZR[0-9a-f]{16})\(", wrapper)
        if callee is None:
            raise RuntimeError(f"{function} did not call its derived implementation")
        derived = generated_function_by_symbol(generated, callee.group(1))
        if "switch(" in derived or "case " in derived:
            raise RuntimeError(f"{function} derived a variant-by-variant comparison")


def check_cfg_compaction(rustc: str, src: str, work: str) -> None:
    output = os.path.join(work, "cfg-compaction")
    result = invoke(
        rustc,
        src,
        output,
        ["--crate-name", "codegen_cfg_compaction", "-Cemit-cpp-only"],
    )
    expect_ok(result, "CFG compaction codegen")
    generated = Path(output + ".cpp").read_text()
    reject_detailed_codegen_comments(generated)
    require_compact_cpp_syntax(generated)

    call_return = generated_function(generated, "trustme_call_then_return")
    if re.search(r"\bgoto bb\d+;|^bb\d+:$", call_return, re.MULTILINE):
        raise RuntimeError("call followed by a single-predecessor return was not merged")

    no_op_drop = generated_function(generated, "trustme_noop_drop_chain")
    if re.search(r"\bgoto bb\d+;|^bb\d+:$", no_op_drop, re.MULTILINE):
        raise RuntimeError("monomorphized no-op drop block was not forwarded")

    branch = generated_function(generated, "trustme_branch_fallthrough")
    if len(re.findall(r"\bgoto bb\d+;", branch)) != 1:
        raise RuntimeError("conditional branch did not use one physical fallthrough")
    labels = set(re.findall(r"^bb(\d+):$", branch, re.MULTILINE))
    targets = set(re.findall(r"\bgoto bb(\d+);", branch))
    if labels != targets:
        raise RuntimeError(f"basic block labels {labels!r} do not match goto targets {targets!r}")

    locations = re.search(
        r"const trustme_caller_location trustme_caller_locations\[\] = \{\n(.*?)\n\};",
        generated,
        re.DOTALL,
    )
    references = re.findall(r"&trustme_caller_locations\[(\d+)\]", generated)
    if locations is None or locations.group(1).count("{{(void*)") != len(set(references)):
        raise RuntimeError("caller location table does not match its referenced entries")
    if not any(references.count(index) == 2 for index in set(references)):
        raise RuntimeError("duplicate monomorphized caller locations were not interned")
    if "static const trustme_caller_location trustme_" in generated:
        raise RuntimeError("caller location was still emitted as a function-local static")


def check_prototype_order(rustc: str, src: str, work: str) -> None:
    output = os.path.join(work, "prototype-order")
    result = invoke(
        rustc,
        src,
        output,
        ["--crate-name", "codegen_prototype_order", "-Cemit-cpp-only"],
    )
    expect_ok(result, "function prototype ordering codegen")
    generated = Path(output + ".cpp").read_text()
    reject_detailed_codegen_comments(generated)
    require_compact_cpp_syntax(generated)

    mangled = re.findall(r"\bZR[A-Za-z0-9_$]*", generated)
    if not mangled or any(re.fullmatch(r"ZR[0-9a-f]{16}", symbol) is None for symbol in mangled):
        raise RuntimeError("generated identifiers do not use short stable hashes")
    if "#define ZRe2bff76835446371 trustme_order_root\n" not in generated:
        raise RuntimeError("stable mangling changed for trustme_order_root")

    functions = (
        "trustme_order_leaf",
        "trustme_order_middle",
        "trustme_five_arguments",
        "trustme_six_arguments",
        "trustme_recursive_a",
        "trustme_recursive_b",
        "trustme_order_root",
    )
    headers = {name: generated_function_headers(generated, name) for name in functions}
    prototypes = {
        name
        for name, entries in headers.items()
        if any(terminator == ";" for _, terminator in entries)
    }
    if prototypes != {"trustme_recursive_a", "trustme_recursive_b"}:
        raise RuntimeError(f"unexpected internal prototypes: {sorted(prototypes)!r}")

    for name in functions:
        for position, terminator in headers[name]:
            line_end = generated.find("\n", position)
            if terminator not in generated[position:line_end]:
                if name != "trustme_six_arguments":
                    raise RuntimeError(f"{name} function header is split across lines")
            elif name == "trustme_six_arguments":
                raise RuntimeError("six-argument function header was not split across lines")

    for name in functions:
        body = generated_function(generated, name)
        body_end = generated.find(body) + len(body)
        if generated[body_end:body_end + 1] != "\n":
            raise RuntimeError(f"{name} has no blank line after its definition")

    padded_call = re.search(r"\bZR[0-9a-f]{16}\( |\b(?:memcpy|memmove|memset|memcmp)\( ", generated)
    if padded_call:
        raise RuntimeError(f"generated call contains space after opening parenthesis: {padded_call.group()!r}")
    if re.search(r"^[ \t].*\bZR[0-9a-f]{16}\([^\n;]* \);", generated, re.MULTILINE):
        raise RuntimeError("generated call contains space before closing parenthesis")

    definitions = {
        name: next(position for position, terminator in entries if terminator == "{")
        for name, entries in headers.items()
    }
    if not definitions["trustme_order_leaf"] < definitions["trustme_order_middle"] < definitions["trustme_order_root"]:
        raise RuntimeError("function definitions are not ordered callee before caller")
    external = generated.find('asm("trustme_order_external")')
    if external < 0 or external > definitions["trustme_order_leaf"]:
        raise RuntimeError("external function declaration was not emitted before definitions")


def main() -> int:
    if len(sys.argv) != 12:
        raise SystemExit(
            "usage: test_codegen_options.py "
            "RUSTC MIR_RS CFG_RS LINK_RS UNWIND_RS SWITCH_RS FIELDLESS_RS "
            "CFG_COMPACT_RS PROTO_RS LIBSTD_TAR STAMP"
        )
    (
        rustc,
        mir_src,
        cfg_src,
        link_src,
        unwind_src,
        switch_src,
        fieldless_src,
        cfg_compact_src,
        proto_src,
        libstd_tar,
        stamp,
    ) = map(os.path.abspath, sys.argv[1:])

    with tempfile.TemporaryDirectory(prefix="trustme-codegen-options-") as work:
        mir_cases = [
            ("level0", ["-Copt-level=0"], False),
            ("level1", ["-C", "opt-level=1"], False),
            ("level2", ["-Copt-level=2"], True),
            ("level3", ["-C", "opt-level=3"], True),
            ("size", ["-Copt-level=s"], True),
            ("size_min", ["-Copt-level=z"], True),
            ("rightmost_c", ["-O", "-Copt-level=0"], False),
            ("rightmost_o", ["-Copt-level=0", "-O"], True),
        ]
        for name, args, expected_inline in mir_cases:
            actual_inline = ordinary_call_is_inlined(compile_mir(rustc, mir_src, work, name, args))
            if actual_inline != expected_inline:
                raise RuntimeError(f"{name}: ordinary_call inline={actual_inline}, expected {expected_inline}")

        check_cfg(rustc, cfg_src, work, "default", True, [])
        check_cfg(rustc, cfg_src, work, "optimized", False, ["-O"])
        check_cfg(rustc, cfg_src, work, "level0-cfg", True, ["-Copt-level=0"])
        check_cfg(rustc, cfg_src, work, "size-cfg", False, ["-Copt-level=s"])
        check_cfg(rustc, cfg_src, work, "bare-debug", True, ["-O", "-C", "debug-assertions"])
        check_cfg(rustc, cfg_src, work, "yes-debug", True, ["-O", "-Cdebug-assertions=yes"])
        check_cfg(rustc, cfg_src, work, "no-debug", False, ["-Cdebug-assertions=no"])
        check_cfg(rustc, cfg_src, work, "off-debug", False, ["-C", "debug-assertions=off"])

        expect_error(
            invoke(rustc, cfg_src, os.path.join(work, "invalid-level"), ["-Copt-level=4"]),
            "invalid opt-level",
            "optimization level",
        )
        expect_error(
            invoke(rustc, cfg_src, os.path.join(work, "invalid-debug"), ["-Cdebug-assertions=maybe"]),
            "invalid debug-assertions",
            "debug-assertions",
        )

        expected_codegen_flags = {"0": "-O0", "1": "-O1", "s": "-Os", "z": "-Oz"}
        for level, expected_flag in expected_codegen_flags.items():
            flags = codegen_flags(rustc, mir_src, work, f"codegen-{level}", [f"-Copt-level={level}"])
            if expected_flag not in flags:
                raise RuntimeError(f"opt-level={level} did not emit {expected_flag}: {flags!r}")

        debuginfo_cases = [
            ("none-number", ["-Cdebuginfo=0"], None),
            ("none-name", ["-Cdebuginfo=none"], None),
            ("line-directives", ["-Cdebuginfo=line-directives-only"], "-g1"),
            ("line-tables", ["-Cdebuginfo=line-tables-only"], "-g1"),
            ("limited-number", ["-Cdebuginfo=1"], "-g1"),
            ("limited-name", ["-Cdebuginfo=limited"], "-g1"),
            ("full-number", ["-Cdebuginfo=2"], "-g"),
            ("full-name", ["-Cdebuginfo=full"], "-g"),
            ("short", ["-g"], "-g"),
        ]
        for name, args, expected_flag in debuginfo_cases:
            flags = codegen_flags(rustc, mir_src, work, f"debuginfo-{name}", args)
            actual_flags = [flag for flag in flags if flag == "-g" or flag.startswith("-g")]
            expected_flags = [] if expected_flag is None else [expected_flag]
            if actual_flags != expected_flags:
                raise RuntimeError(f"debuginfo={name} emitted {actual_flags!r}, expected {expected_flags!r}")

        expect_error(
            invoke(rustc, cfg_src, os.path.join(work, "invalid-debuginfo"), ["-Cdebuginfo=3"]),
            "invalid debuginfo",
            "debuginfo",
        )
        check_codegen_prelude(rustc, mir_src, work)
        check_link_args(rustc, link_src, work)
        check_unwind_cleanup(rustc, unwind_src, work)
        check_enum_switch_compaction(rustc, switch_src, work)
        check_fieldless_enum_derive(rustc, fieldless_src, libstd_tar, work)
        check_cfg_compaction(rustc, cfg_compact_src, work)
        check_prototype_order(rustc, proto_src, work)

    os.makedirs(os.path.dirname(stamp), exist_ok=True)
    Path(stamp).touch()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
