// serde_core's `ArrayVisitor<[T; 32]>::visit_seq` builds its array from 32
// `match tri!(seq.next_element()) { Some(val) => val, None => return .. }`.
// Every scrutinee is a temporary that lives to the end of the statement with
// its payload moved out, so each cleanup path drops it by its discriminant.
// rustc's drop tree keeps one node per (local, continuation) and elaborates
// the partial move once per node; our cleanup chains shared only whole-slot
// drops, built a private copy for each partially-moved value, and so gave
// every chain above it a private copy too - MIR cubic in the element count:
// 549 236 blocks for 32 elements, serde_core 72 s and 2.8 GB. This is the
// same shape with 128 elements.
pub fn visit<T, I: Iterator<Item = T>>(mut it: I) -> Result<[T; 128], usize> {
    Ok([
        match it.next() { Some(v) => v, None => return Err(0) },
        match it.next() { Some(v) => v, None => return Err(1) },
        match it.next() { Some(v) => v, None => return Err(2) },
        match it.next() { Some(v) => v, None => return Err(3) },
        match it.next() { Some(v) => v, None => return Err(4) },
        match it.next() { Some(v) => v, None => return Err(5) },
        match it.next() { Some(v) => v, None => return Err(6) },
        match it.next() { Some(v) => v, None => return Err(7) },
        match it.next() { Some(v) => v, None => return Err(8) },
        match it.next() { Some(v) => v, None => return Err(9) },
        match it.next() { Some(v) => v, None => return Err(10) },
        match it.next() { Some(v) => v, None => return Err(11) },
        match it.next() { Some(v) => v, None => return Err(12) },
        match it.next() { Some(v) => v, None => return Err(13) },
        match it.next() { Some(v) => v, None => return Err(14) },
        match it.next() { Some(v) => v, None => return Err(15) },
        match it.next() { Some(v) => v, None => return Err(16) },
        match it.next() { Some(v) => v, None => return Err(17) },
        match it.next() { Some(v) => v, None => return Err(18) },
        match it.next() { Some(v) => v, None => return Err(19) },
        match it.next() { Some(v) => v, None => return Err(20) },
        match it.next() { Some(v) => v, None => return Err(21) },
        match it.next() { Some(v) => v, None => return Err(22) },
        match it.next() { Some(v) => v, None => return Err(23) },
        match it.next() { Some(v) => v, None => return Err(24) },
        match it.next() { Some(v) => v, None => return Err(25) },
        match it.next() { Some(v) => v, None => return Err(26) },
        match it.next() { Some(v) => v, None => return Err(27) },
        match it.next() { Some(v) => v, None => return Err(28) },
        match it.next() { Some(v) => v, None => return Err(29) },
        match it.next() { Some(v) => v, None => return Err(30) },
        match it.next() { Some(v) => v, None => return Err(31) },
        match it.next() { Some(v) => v, None => return Err(32) },
        match it.next() { Some(v) => v, None => return Err(33) },
        match it.next() { Some(v) => v, None => return Err(34) },
        match it.next() { Some(v) => v, None => return Err(35) },
        match it.next() { Some(v) => v, None => return Err(36) },
        match it.next() { Some(v) => v, None => return Err(37) },
        match it.next() { Some(v) => v, None => return Err(38) },
        match it.next() { Some(v) => v, None => return Err(39) },
        match it.next() { Some(v) => v, None => return Err(40) },
        match it.next() { Some(v) => v, None => return Err(41) },
        match it.next() { Some(v) => v, None => return Err(42) },
        match it.next() { Some(v) => v, None => return Err(43) },
        match it.next() { Some(v) => v, None => return Err(44) },
        match it.next() { Some(v) => v, None => return Err(45) },
        match it.next() { Some(v) => v, None => return Err(46) },
        match it.next() { Some(v) => v, None => return Err(47) },
        match it.next() { Some(v) => v, None => return Err(48) },
        match it.next() { Some(v) => v, None => return Err(49) },
        match it.next() { Some(v) => v, None => return Err(50) },
        match it.next() { Some(v) => v, None => return Err(51) },
        match it.next() { Some(v) => v, None => return Err(52) },
        match it.next() { Some(v) => v, None => return Err(53) },
        match it.next() { Some(v) => v, None => return Err(54) },
        match it.next() { Some(v) => v, None => return Err(55) },
        match it.next() { Some(v) => v, None => return Err(56) },
        match it.next() { Some(v) => v, None => return Err(57) },
        match it.next() { Some(v) => v, None => return Err(58) },
        match it.next() { Some(v) => v, None => return Err(59) },
        match it.next() { Some(v) => v, None => return Err(60) },
        match it.next() { Some(v) => v, None => return Err(61) },
        match it.next() { Some(v) => v, None => return Err(62) },
        match it.next() { Some(v) => v, None => return Err(63) },
        match it.next() { Some(v) => v, None => return Err(64) },
        match it.next() { Some(v) => v, None => return Err(65) },
        match it.next() { Some(v) => v, None => return Err(66) },
        match it.next() { Some(v) => v, None => return Err(67) },
        match it.next() { Some(v) => v, None => return Err(68) },
        match it.next() { Some(v) => v, None => return Err(69) },
        match it.next() { Some(v) => v, None => return Err(70) },
        match it.next() { Some(v) => v, None => return Err(71) },
        match it.next() { Some(v) => v, None => return Err(72) },
        match it.next() { Some(v) => v, None => return Err(73) },
        match it.next() { Some(v) => v, None => return Err(74) },
        match it.next() { Some(v) => v, None => return Err(75) },
        match it.next() { Some(v) => v, None => return Err(76) },
        match it.next() { Some(v) => v, None => return Err(77) },
        match it.next() { Some(v) => v, None => return Err(78) },
        match it.next() { Some(v) => v, None => return Err(79) },
        match it.next() { Some(v) => v, None => return Err(80) },
        match it.next() { Some(v) => v, None => return Err(81) },
        match it.next() { Some(v) => v, None => return Err(82) },
        match it.next() { Some(v) => v, None => return Err(83) },
        match it.next() { Some(v) => v, None => return Err(84) },
        match it.next() { Some(v) => v, None => return Err(85) },
        match it.next() { Some(v) => v, None => return Err(86) },
        match it.next() { Some(v) => v, None => return Err(87) },
        match it.next() { Some(v) => v, None => return Err(88) },
        match it.next() { Some(v) => v, None => return Err(89) },
        match it.next() { Some(v) => v, None => return Err(90) },
        match it.next() { Some(v) => v, None => return Err(91) },
        match it.next() { Some(v) => v, None => return Err(92) },
        match it.next() { Some(v) => v, None => return Err(93) },
        match it.next() { Some(v) => v, None => return Err(94) },
        match it.next() { Some(v) => v, None => return Err(95) },
        match it.next() { Some(v) => v, None => return Err(96) },
        match it.next() { Some(v) => v, None => return Err(97) },
        match it.next() { Some(v) => v, None => return Err(98) },
        match it.next() { Some(v) => v, None => return Err(99) },
        match it.next() { Some(v) => v, None => return Err(100) },
        match it.next() { Some(v) => v, None => return Err(101) },
        match it.next() { Some(v) => v, None => return Err(102) },
        match it.next() { Some(v) => v, None => return Err(103) },
        match it.next() { Some(v) => v, None => return Err(104) },
        match it.next() { Some(v) => v, None => return Err(105) },
        match it.next() { Some(v) => v, None => return Err(106) },
        match it.next() { Some(v) => v, None => return Err(107) },
        match it.next() { Some(v) => v, None => return Err(108) },
        match it.next() { Some(v) => v, None => return Err(109) },
        match it.next() { Some(v) => v, None => return Err(110) },
        match it.next() { Some(v) => v, None => return Err(111) },
        match it.next() { Some(v) => v, None => return Err(112) },
        match it.next() { Some(v) => v, None => return Err(113) },
        match it.next() { Some(v) => v, None => return Err(114) },
        match it.next() { Some(v) => v, None => return Err(115) },
        match it.next() { Some(v) => v, None => return Err(116) },
        match it.next() { Some(v) => v, None => return Err(117) },
        match it.next() { Some(v) => v, None => return Err(118) },
        match it.next() { Some(v) => v, None => return Err(119) },
        match it.next() { Some(v) => v, None => return Err(120) },
        match it.next() { Some(v) => v, None => return Err(121) },
        match it.next() { Some(v) => v, None => return Err(122) },
        match it.next() { Some(v) => v, None => return Err(123) },
        match it.next() { Some(v) => v, None => return Err(124) },
        match it.next() { Some(v) => v, None => return Err(125) },
        match it.next() { Some(v) => v, None => return Err(126) },
        match it.next() { Some(v) => v, None => return Err(127) }
    ])
}
fn main() {
    let v: Vec<String> = (0..128).map(|i| i.to_string()).collect();
    let r = visit(v.into_iter()).unwrap();
    assert_eq!(r.len(), 128);
    assert_eq!(r[127], "127");
    let short: Vec<String> = (0..5).map(|i| i.to_string()).collect();
    assert_eq!(visit(short.into_iter()).err(), Some(5));
}
